'use client'
import { useState } from 'react'
import toast from 'react-hot-toast'
import DashLayout from '../dashboard/layout'
import { useStore } from '@/lib/store'
import { generateWorkout, completeWorkout } from '@/lib/api'

const MUSCLES = ['Full Body','Chest + Shoulders','Back + Biceps','Legs + Glutes','Core + Abs','Arms']
const EQUIPMENT = ['No Equipment','Dumbbells','Barbell','Full Gym','Resistance Bands']
const DURATIONS = [20,30,45,60,90]

export default function WorkoutPage() {
  const { user, updateUser } = useStore()
  const [params, setParams] = useState({ muscle_group:'Full Body', duration_min:45, equipment:'Full Gym', intensity:'Moderate' })
  const [workout, setWorkout] = useState<any>(null)
  const [generating, setGenerating] = useState(false)
  const [active, setActive] = useState(false)
  const [completedSets, setCompletedSets] = useState<Record<string,boolean>>({})
  const [seconds, setSeconds] = useState(0)
  const [timerRef, setTimerRef] = useState<any>(null)

  async function generate() {
    setGenerating(true)
    setWorkout(null)
    try {
      const r = await generateWorkout(params)
      setWorkout(r.data)
      toast.success('Workout generated by AI ⚡')
    } catch { toast.error('Could not generate workout — check your API key') }
    finally { setGenerating(false) }
  }

  function startWorkout() {
    setActive(true)
    setCompletedSets({})
    setSeconds(0)
    const ref = setInterval(() => setSeconds(s => s+1), 1000)
    setTimerRef(ref)
  }

  async function finishWorkout() {
    if (timerRef) clearInterval(timerRef)
    setActive(false)
    try {
      const kcal = workout?.estimated_kcal
      const r = await completeWorkout(workout.id, kcal)
      updateUser({ streak: r.data.new_streak, total_workouts: r.data.total_workouts, xp: (user?.xp || 0) + 200 })
      toast.success(`Workout complete! +200 XP 🏆`)
      setWorkout(null)
    } catch { toast.error('Could not save workout') }
  }

  const fmt = (s: number) => `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`
  const totalSets = workout ? workout.exercises.reduce((a: number, e: any) => a + e.sets, 0) : 0
  const doneSets = Object.values(completedSets).filter(Boolean).length
  const pct = totalSets ? Math.round(doneSets/totalSets*100) : 0

  return (
    <DashLayout>
      {/* Active Workout Overlay */}
      {active && workout && (
        <div style={{ position:'fixed', inset:0, background:'var(--bg)', zIndex:200, display:'flex', flexDirection:'column', maxWidth:520, margin:'0 auto' }}>
          <div style={{ padding:'20px', borderBottom:'1px solid var(--border)', display:'flex', justifyContent:'space-between', alignItems:'center' }}>
            <div>
              <div style={{ fontSize:11, color:'var(--muted2)', textTransform:'uppercase', letterSpacing:1 }}>Active Workout</div>
              <div className="font-syne" style={{ fontSize:18, fontWeight:800 }}>{workout.title}</div>
            </div>
            <div className="font-syne" style={{ fontSize:36, fontWeight:800, color:'var(--accent)' }}>{fmt(seconds)}</div>
          </div>

          <div style={{ flex:1, overflowY:'auto', padding:20 }}>
            <div className="pbar" style={{ marginBottom:12 }}><div className="pbar-fill" style={{ width:`${pct}%` }}/></div>
            <div style={{ fontSize:12, color:'var(--muted2)', marginBottom:20 }}>{doneSets}/{totalSets} sets complete</div>

            {workout.exercises.map((ex: any, ei: number) => {
              const allDone = Array.from({length:ex.sets},(_,si) => completedSets[`${ei}-${si}`]).every(Boolean)
              return (
                <div key={ei} style={{ background: allDone ? 'var(--s2)' : 'var(--s1)', border:`1px solid ${allDone ? 'var(--border)' : 'rgba(232,255,71,0.2)'}`,
                  borderRadius:16, padding:'16px 20px', marginBottom:12, opacity: allDone ? 0.6 : 1, transition:'all 0.3s' }}>
                  <div className="font-syne" style={{ fontSize:17, fontWeight:700, marginBottom:4 }}>{ex.name}</div>
                  <div style={{ fontSize:12, color:'var(--muted2)', marginBottom:12 }}>{ex.sets}×{ex.reps} · Rest {ex.rest_seconds}s · {ex.tip}</div>
                  <div style={{ display:'flex', gap:8, flexWrap:'wrap' }}>
                    {Array.from({length:ex.sets},(_,si) => {
                      const key = `${ei}-${si}`
                      const done = !!completedSets[key]
                      return (
                        <button key={si} onClick={() => setCompletedSets(c => ({ ...c, [key]: !done }))}
                          style={{ width:40, height:40, borderRadius:10, border:`1px solid ${done ? 'var(--accent)' : 'var(--border2)'}`,
                            background: done ? 'var(--accent)' : 'var(--s2)', color: done ? '#060608' : 'var(--text)',
                            cursor:'pointer', fontWeight:700, fontSize:13, transition:'all 0.2s' }}>
                          {si+1}
                        </button>
                      )
                    })}
                  </div>
                </div>
              )
            })}
          </div>

          <div style={{ padding:'16px 20px', borderTop:'1px solid var(--border)', display:'flex', gap:10 }}>
            <button className="btn-ghost" onClick={() => { clearInterval(timerRef); setActive(false) }} style={{ flex:1, padding:'13px' }}>End</button>
            <button className="btn-primary" onClick={finishWorkout} style={{ flex:2, padding:'13px', fontSize:14 }}>✓ Complete Workout</button>
          </div>
        </div>
      )}

      <div style={{ padding:'20px 20px 0' }}>
        <div style={{ fontSize:11, textTransform:'uppercase', letterSpacing:1, color:'var(--muted2)' }}>AI-Powered</div>
        <div className="font-syne fade-up" style={{ fontSize:28, fontWeight:800, marginBottom:24 }}>Generate Workout</div>

        {/* Generator Card */}
        <div className="card fade-up-1" style={{ marginBottom:20 }}>
          <div style={{ display:'grid', gridTemplateColumns:'1fr 1fr', gap:12, marginBottom:16 }}>
            <div>
              <div style={{ fontSize:11, textTransform:'uppercase', letterSpacing:1, color:'var(--muted2)', marginBottom:8 }}>Muscle Group</div>
              <select className="forge-input forge-select" value={params.muscle_group} onChange={e => setParams(p => ({...p, muscle_group: e.target.value}))}>
                {MUSCLES.map(m => <option key={m}>{m}</option>)}
              </select>
            </div>
            <div>
              <div style={{ fontSize:11, textTransform:'uppercase', letterSpacing:1, color:'var(--muted2)', marginBottom:8 }}>Equipment</div>
              <select className="forge-input forge-select" value={params.equipment} onChange={e => setParams(p => ({...p, equipment: e.target.value}))}>
                {EQUIPMENT.map(e => <option key={e}>{e}</option>)}
              </select>
            </div>
          </div>
          <div style={{ marginBottom:16 }}>
            <div style={{ fontSize:11, textTransform:'uppercase', letterSpacing:1, color:'var(--muted2)', marginBottom:8 }}>Duration: {params.duration_min} min</div>
            <div style={{ display:'flex', gap:8 }}>
              {DURATIONS.map(d => (
                <button key={d} onClick={() => setParams(p => ({...p, duration_min:d}))}
                  style={{ flex:1, padding:'8px 0', borderRadius:10, border:`1px solid ${params.duration_min===d ? 'var(--accent)' : 'var(--border2)'}`,
                    background: params.duration_min===d ? 'rgba(232,255,71,0.1)' : 'var(--s2)',
                    color: params.duration_min===d ? 'var(--accent)' : 'var(--muted2)',
                    cursor:'pointer', fontSize:12, fontWeight:500 }}>{d}</button>
              ))}
            </div>
          </div>
          <button className="btn-primary" onClick={generate} disabled={generating}
            style={{ width:'100%', padding:'15px', fontSize:15, display:'flex', alignItems:'center', justifyContent:'center', gap:8 }}>
            {generating ? <><span className="spinner"/> Generating your plan...</> : '⚡ Generate AI Workout'}
          </button>
        </div>

        {/* Generated Workout */}
        {workout && (
          <div className="fade-up" style={{ marginBottom:20 }}>
            <div style={{ background:'rgba(232,255,71,0.06)', border:'1px solid rgba(232,255,71,0.2)', borderRadius:20, padding:20, marginBottom:12 }}>
              <div style={{ fontSize:11, textTransform:'uppercase', letterSpacing:1, color:'var(--accent)', marginBottom:6 }}>🤖 AI Coach Note</div>
              <div style={{ fontSize:14, lineHeight:1.6, color:'var(--text)' }}>{workout.coach_note}</div>
            </div>

            <div className="card" style={{ marginBottom:12 }}>
              <div className="font-syne" style={{ fontSize:22, fontWeight:800, marginBottom:6 }}>{workout.title}</div>
              <div style={{ display:'flex', gap:12, marginBottom:16 }}>
                <span className="chip chip-yellow">⏱ {workout.duration_min} min</span>
                <span className="chip chip-green">🔥 {workout.estimated_kcal} kcal</span>
                <span className="chip chip-orange">💪 {user?.level || 'Intermediate'}</span>
              </div>

              {workout.warmup && (
                <div style={{ padding:'12px 14px', background:'var(--s2)', borderRadius:12, marginBottom:16, fontSize:13, color:'var(--muted2)', lineHeight:1.6 }}>
                  <strong style={{ color:'var(--text)' }}>Warm-up:</strong> {workout.warmup}
                </div>
              )}

              {workout.exercises.map((ex: any, i: number) => (
                <div key={i} style={{ display:'flex', alignItems:'flex-start', gap:12, padding:'12px 0', borderBottom:`1px solid var(--border)` }}>
                  <div className="font-syne" style={{ fontSize:18, fontWeight:800, color:'var(--accent)', minWidth:28 }}>{i+1}</div>
                  <div style={{ flex:1 }}>
                    <div style={{ fontWeight:500, fontSize:14 }}>{ex.name}</div>
                    <div style={{ fontSize:12, color:'var(--muted2)', marginTop:2 }}>{ex.sets} sets × {ex.reps} reps · Rest {ex.rest_seconds}s</div>
                    <div style={{ fontSize:11, color:'var(--accent2)', marginTop:4 }}>💡 {ex.tip}</div>
                  </div>
                  <span style={{ fontSize:11, padding:'3px 8px', borderRadius:20, background:'var(--s2)', color:'var(--muted2)' }}>{ex.muscle}</span>
                </div>
              ))}

              {workout.cooldown && (
                <div style={{ padding:'12px 14px', background:'var(--s2)', borderRadius:12, marginTop:16, fontSize:13, color:'var(--muted2)', lineHeight:1.6 }}>
                  <strong style={{ color:'var(--text)' }}>Cool-down:</strong> {workout.cooldown}
                </div>
              )}
            </div>

            <button className="btn-primary" onClick={startWorkout}
              style={{ width:'100%', padding:'16px', fontSize:16 }}>▶ Start Workout</button>
          </div>
        )}
      </div>
    </DashLayout>
  )
}
